apiVersion : apps/v1
kind: Deployment
metadata:
  name: xmas 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xmas
  template:
    metadata:
      labels:
        app: xmas 
    spec:
      containers:
        - name: xmas 
          image: xmaslabcr.azurecr.io/xmas
          ports:
          - containerPort: 8080